// SPDX-License-Identifier: Apache-2.0

//! Read a `.kicad_pcb` back as topology and copper.
//!
//! Synth's exporter is deliberately one-way (`synth-kicad` never reads
//! KiCad files), but that is a statement about *import*, not about
//! verification. Once copper is generated by an external router, somebody
//! has to read the result to confirm the router did what it claimed — and
//! the only honest reader is one that looks at the file rather than at
//! the router's summary of it.
//!
//! This is that reader. It is a real s-expression parser rather than a
//! substring scan, because the facts validation depends on — which net a
//! pad belongs to, which layer a track is on, where a pad sits — are
//! exactly the ones a textual search gets wrong in the presence of an
//! identically-named token in an unrelated block.
//!
//! Scope is deliberately narrow: the constructs needed to compare
//! topology and re-derive connectivity. Fields the compiler owns and the
//! validator has no opinion about (silkscreen, 3D models, teardrops,
//! text) are skipped.

// Board geometry is far below f64's 52-bit mantissa: a 100 mm board
// spans 1e8 nm, some seven orders of magnitude under 2^53. The distance
// helpers below therefore square i64 differences as f64 without loss.
#![allow(clippy::cast_precision_loss)]

use std::collections::{BTreeMap, BTreeSet};

/// Nanometres per millimetre, for the integer geometry the connectivity
/// pass works in.
pub const NM_PER_MM: f64 = 1_000_000.0;

/// A point in board coordinates, in nanometres.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
pub struct Point {
    pub x_nm: i64,
    pub y_nm: i64,
}

impl Point {
    #[must_use]
    pub fn new(x_nm: i64, y_nm: i64) -> Self {
        Self { x_nm, y_nm }
    }

    #[must_use]
    pub fn x_mm(&self) -> f64 {
        self.x_nm as f64 / NM_PER_MM
    }

    #[must_use]
    pub fn y_mm(&self) -> f64 {
        self.y_nm as f64 / NM_PER_MM
    }
}

/// Convert millimetres to integer nanometres.
///
/// Rounding rather than truncation matters: a coordinate that lands a few
/// femtometres either side of an integer must hash to the same node as
/// the copper that touches it, or every net appears open.
#[must_use]
pub fn mm_to_nm(mm: f64) -> i64 {
    if !mm.is_finite() {
        return 0;
    }
    (mm * NM_PER_MM).round() as i64
}

/// A parsed s-expression node.
#[derive(Debug, Clone, PartialEq)]
pub enum Node {
    /// A bare token. In KiCad files this is a number, a keyword, or an
    /// unquoted symbol.
    Atom(String),
    /// A parenthesised list, head included as the first element.
    List(Vec<Node>),
}

impl Node {
    /// The head symbol of a list, if this is a list.
    #[must_use]
    pub fn head(&self) -> Option<&str> {
        match self {
            Node::List(items) => items.first().and_then(Node::as_str),
            Node::Atom(_) => None,
        }
    }

    /// The list's elements, excluding the head.
    #[must_use]
    pub fn body(&self) -> &[Node] {
        match self {
            Node::List(items) => items.get(1..).unwrap_or(&[]),
            Node::Atom(_) => &[],
        }
    }

    /// This node's text, whether it is an atom or a quoted string.
    #[must_use]
    pub fn as_str(&self) -> Option<&str> {
        match self {
            Node::Atom(text) => Some(text.as_str()),
            Node::List(_) => None,
        }
    }

    /// The first child list with the given head.
    #[must_use]
    pub fn find(&self, key: &str) -> Option<&Node> {
        self.body().iter().find(|n| n.head() == Some(key))
    }

    /// Every child list with the given head.
    pub fn find_all<'a>(&'a self, key: &'a str) -> impl Iterator<Item = &'a Node> + 'a {
        self.body().iter().filter(move |n| n.head() == Some(key))
    }

    /// The value carried by a child with the given head.
    ///
    /// KiCad uses two shapes for the same idea, and both appear in a
    /// board file: `(version 20260206)` puts the value inside the child,
    /// while `(segment ... (net 5))` puts a bare `net` atom with the value
    /// as its sibling. Reading only one of them silently drops half the
    /// board's net and version data, so both are accepted.
    #[must_use]
    pub fn child_atom(&self, key: &str) -> Option<&str> {
        if let Some(child) = self.find(key) {
            if let Some(value) = child.body().first().and_then(Node::as_str) {
                return Some(value);
            }
        }
        let idx = self.body().iter().position(|n| n.as_str() == Some(key))?;
        self.body().get(idx + 1).and_then(Node::as_str)
    }

    /// The first number carried by a child with the given head.
    #[must_use]
    pub fn child_f64(&self, key: &str) -> Option<f64> {
        self.child_atom(key).and_then(|s| s.parse().ok())
    }

    /// The first integer carried by a child with the given head.
    #[must_use]
    pub fn child_i64(&self, key: &str) -> Option<i64> {
        self.child_atom(key).and_then(|s| s.parse().ok())
    }

    /// The value of a `(property "Name" "Value" ...)` child.
    ///
    /// The name is a bare atom in first position, which is why this is
    /// read positionally rather than through [`Node::child_atom`].
    #[must_use]
    pub fn property(&self, name: &str) -> Option<&str> {
        self.find_all("property")
            .filter(|p| p.body().first().and_then(Node::as_str) == Some(name))
            .find_map(|p| p.body().get(1).and_then(Node::as_str))
    }

    /// The quoted names of a `(layers ...)` child, in file order.
    ///
    /// A `(layers ...)` block is either a list of stackup records
    /// (`(0 "F.Cu" signal)`) or a bare list of names (`"F.Cu" "B.Cu"`),
    /// depending on whether it declares the stackup or one item's layer
    /// membership. A stackup record leads with the layer number rather
    /// than a keyword, so the name is the first element that is not an
    /// integer.
    #[must_use]
    pub fn layer_names(&self) -> Vec<String> {
        // A zone names its layers `(layer "F.Cu")` (singular) while the
        // stackup and a pad use `(layers ...)`. Reading only the plural left
        // every zone with no layer at all, so its pour matched nothing.
        if let Some(layers) = self.find("layers") {
            return layers.body().iter().filter_map(Node::layer_label).collect();
        }
        if let Some(layer) = self.find("layer") {
            return layer.body().iter().filter_map(Node::layer_label).collect();
        }
        Vec::new()
    }

    /// A `(layers ...)` element read as a single layer name.
    ///
    /// Handles both spellings the format uses: a bare quoted name, and a
    /// stackup record that leads with the layer number.
    #[must_use]
    fn layer_label(node: &Node) -> Option<String> {
        match node {
            Node::Atom(name) => Some(name.clone()),
            Node::List(_) => node
                .body()
                .iter()
                .filter_map(Node::as_str)
                .find(|token| token.parse::<i64>().is_err())
                .map(String::from),
        }
    }

    /// The `(net <code> "<name>")` binding carried by a pad or copper item.
    ///
    /// Both halves matter and they disagree often enough to be worth
    /// reading separately: the code is what identifies the net inside one
    /// file, the name is what a human reads. Validating only the name
    /// would let a renumbered net pass unnoticed.
    ///
    /// A board written without a net table carries only the name, as
    /// `(net "net_0")`. That form still returns a binding — with no code —
    /// rather than nothing, because discarding it makes every net on such a
    /// board invisible and a correctly routed board looks like one whose
    /// nets went missing.
    #[must_use]
    pub fn net_binding(&self, key: &str) -> Option<(Option<i64>, Option<String>)> {
        let net = self.find(key).or_else(|| {
            let idx = self.body().iter().position(|n| n.as_str() == Some(key))?;
            self.body().get(idx + 1)
        })?;
        let first = net.body().first().and_then(Node::as_str)?;
        let code = first.parse::<i64>().ok();
        if code.is_some() {
            let name = net
                .body()
                .get(1)
                .and_then(Node::as_str)
                .map(ToString::to_string);
            Some((code, name))
        } else if first.is_empty() {
            None
        } else {
            // Name-only form: the name is the whole binding.
            Some((None, Some(first.to_string())))
        }
    }
}

/// Why a `.kicad_pcb` could not be read.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PcbParseError {
    /// Byte offset where parsing stopped.
    pub offset: usize,
    pub detail: String,
}

impl std::fmt::Display for PcbParseError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "malformed .kicad_pcb at byte {}: {}",
            self.offset, self.detail
        )
    }
}

impl std::error::Error for PcbParseError {}

/// Parse a `.kicad_pcb` into a node tree.
///
/// Handles the three things KiCad files mix freely: `;` line comments,
/// `"..."` quoted strings with backslash escapes, and bare atoms.
///
/// # Errors
/// Returns [`PcbParseError`] with the byte offset where parsing stopped.
pub fn parse_sexpr(text: &str) -> Result<Node, PcbParseError> {
    let bytes = text.as_bytes();
    let mut pos = 0usize;
    let mut stack: Vec<Vec<Node>> = vec![Vec::new()];

    while pos < bytes.len() {
        match bytes[pos] {
            b';' => {
                while pos < bytes.len() && bytes[pos] != b'\n' {
                    pos += 1;
                }
            }
            b'(' => {
                stack.push(Vec::new());
                pos += 1;
            }
            b')' => {
                if stack.len() == 1 {
                    return Err(PcbParseError {
                        offset: pos,
                        detail: "unbalanced `)`".to_string(),
                    });
                }
                let items = stack.pop().unwrap_or_default();
                let node = Node::List(items);
                // The root frame is never popped: `stack.len() == 1` is
                // checked before every pop, so this is always Some.
                if let Some(frame) = stack.last_mut() {
                    frame.push(node);
                }
                pos += 1;
            }
            b'"' => {
                let (value, next) = read_quoted(text, pos)?;
                if let Some(frame) = stack.last_mut() {
                    frame.push(Node::Atom(value));
                }
                pos = next;
            }
            b' ' | b'\t' | b'\r' | b'\n' => pos += 1,
            _ => {
                let start = pos;
                while pos < bytes.len()
                    && !matches!(
                        bytes[pos],
                        b'(' | b')' | b'"' | b' ' | b'\t' | b'\r' | b'\n'
                    )
                {
                    pos += 1;
                }
                let token = text[start..pos].to_string();
                if let Some(frame) = stack.last_mut() {
                    frame.push(Node::Atom(token));
                }
            }
        }
    }

    if stack.len() != 1 {
        return Err(PcbParseError {
            offset: text.len(),
            detail: format!("{} unclosed `(`", stack.len() - 1),
        });
    }
    let mut root = stack.pop().unwrap_or_default();
    if root.len() != 1 {
        return Err(PcbParseError {
            offset: 0,
            detail: format!("expected exactly one top-level list, found {}", root.len()),
        });
    }
    Ok(root.remove(0))
}

fn read_quoted(text: &str, start: usize) -> Result<(String, usize), PcbParseError> {
    let bytes = text.as_bytes();
    let mut pos = start + 1;
    let mut out = String::new();
    while pos < bytes.len() {
        match bytes[pos] {
            b'"' => return Ok((out, pos + 1)),
            b'\\' if pos + 1 < bytes.len() => {
                // KiCad escapes the quote and the backslash; everything
                // else passes through so a Windows path in a 3D model
                // reference survives intact.
                let next = bytes[pos + 1];
                if next == b'"' || next == b'\\' {
                    out.push(next as char);
                } else {
                    out.push('\\');
                    out.push(next as char);
                }
                pos += 2;
            }
            _ => {
                let ch_start = pos;
                pos += text[ch_start..].chars().next().map_or(1, char::len_utf8);
                out.push_str(&text[ch_start..pos]);
            }
        }
    }
    Err(PcbParseError {
        offset: start,
        detail: "unterminated quoted string".to_string(),
    })
}

/// A pad as it appears on the board, with its net resolved.
#[derive(Debug, Clone, PartialEq)]
pub struct Pad {
    pub footprint: String,
    pub number: String,
    pub kind: String,
    pub shape: String,
    /// Absolute position on the board, in nanometres.
    pub at: Point,
    pub size_nm: (i64, i64),
    /// Orientation of the pad's own axes in the board frame, in degrees:
    /// the footprint's rotation plus the pad's local angle, negated for a
    /// footprint on the back. Needed because a rectangular pad's extent is
    /// only meaningful along its own axes.
    pub rotation_deg: f64,
    pub layers: Vec<String>,
    /// Net code as written in the file, if the pad carries one.
    pub net: Option<u32>,
    /// Net name as written in the file, if the pad carries one.
    pub net_name: Option<String>,
}

impl Pad {
    /// Copper radius used for **connectivity**, in nanometres.
    ///
    /// The larger half-dimension is used so a rectangular pad behaves
    /// like the disc that inscribes it. Being conservative here in the
    /// narrow direction would report false opens on fine-pitch parts,
    /// which is the more damaging direction for this check to err.
    ///
    /// That bias makes this radius wrong for any check that *reports a
    /// violation*. On a 1.95 × 0.6 mm SOIC pad the disc reaches 0.975 mm
    /// from the centre while the copper reaches 0.3 mm across the narrow
    /// axis, so it covers 0.675 mm of bare laminate on each long side.
    /// Deciding "inside a pad" from it invents violations against copper
    /// that is comfortably clear. Use [`Self::contains_point`] there.
    #[must_use]
    pub fn radius_nm(&self) -> i64 {
        self.size_nm.0.max(self.size_nm.1) / 2
    }

    /// Whether `point` lies on this pad's copper.
    ///
    /// Exact where [`Self::radius_nm`] is deliberately generous: the point
    /// is taken into the pad's own rotated frame and tested against the
    /// real shape. Unknown shapes fall back to the rectangle, which is the
    /// aperture KiCad draws for `custom` pads' bounding box and never
    /// smaller than the drawn copper for the shapes it names.
    #[must_use]
    pub fn contains_point(&self, point: Point) -> bool {
        let (half_x, half_y) = (self.size_nm.0 as f64 / 2.0, self.size_nm.1 as f64 / 2.0);
        if half_x <= 0.0 || half_y <= 0.0 {
            return false;
        }
        // Into the pad's frame: translate to its centre, then rotate by
        // -rotation so the pad's axes become the coordinate axes.
        let (dx, dy) = (
            (point.x_nm - self.at.x_nm) as f64,
            (point.y_nm - self.at.y_nm) as f64,
        );
        let theta = -self.rotation_deg.to_radians();
        let (cos, sin) = (theta.cos(), theta.sin());
        let local_x = dx * cos - dy * sin;
        let local_y = dx * sin + dy * cos;

        match self.shape.as_str() {
            // A circle's diameter is the first size element; KiCad writes
            // both the same, but the first is the authoritative one.
            "circle" => local_x.hypot(local_y) <= half_x,
            // An obround/oval pad is an ellipse for containment purposes.
            "oval" => (local_x / half_x).powi(2) + (local_y / half_y).powi(2) <= 1.0,
            // `rect`, `roundrect`, `trapezoid`, `custom`, and anything new.
            // A roundrect's clipped corners are inside this rectangle, so a
            // via centred in a corner notch still reads as inside the pad.
            // That residue is bounded by the corner radius — tens of
            // micrometres — rather than by the pad's aspect ratio, and
            // resolving it needs the `roundrect_rratio` the parser does not
            // read today.
            _ => local_x.abs() <= half_x && local_y.abs() <= half_y,
        }
    }

    /// Whether this pad carries copper on `layer`.
    #[must_use]
    pub fn on_layer(&self, layer: &str) -> bool {
        self.layers.iter().any(|l| l == layer)
    }

    /// A stable identity for reporting: `U1.3`.
    #[must_use]
    pub fn id(&self) -> String {
        format!("{}.{}", self.footprint, self.number)
    }
}

/// A footprint instance on the board.
#[derive(Debug, Clone, PartialEq)]
pub struct Footprint {
    pub reference: String,
    pub lib_id: String,
    pub at: Point,
    pub layer: String,
    pub rotation_deg: f64,
    pub pads: Vec<Pad>,
}

/// A track segment.
#[derive(Debug, Clone, PartialEq)]
pub struct Segment {
    pub net: Option<u32>,
    /// Net name as written, kept so a board written without a net table can
    /// still be keyed (see `PcbBoard::rebind_nets_by_name`).
    pub net_name: Option<String>,
    pub layer: String,
    pub start: Point,
    pub end: Point,
    pub width_nm: i64,
}

/// A via.
#[derive(Debug, Clone, PartialEq)]
pub struct Via {
    pub net: Option<u32>,
    /// Net name as written, for the same reason as [`Segment::net_name`].
    pub net_name: Option<String>,
    pub at: Point,
    pub size_nm: i64,
    pub drill_nm: i64,
    pub layers: Vec<String>,
}

/// A copper zone.
#[derive(Debug, Clone, PartialEq)]
pub struct Zone {
    pub net: Option<u32>,
    pub net_name: Option<String>,
    pub layers: Vec<String>,
    /// Outlines of the pour, per layer, as closed polygons in board
    /// coordinates.
    ///
    /// Read from the declared outline rather than the `filled_polygon` that
    /// KiCad only writes after a refill. The independent check refills zones
    /// itself, so the declared outline is what it can rely on being there —
    /// and a ground net connected through a plane is connected through this
    /// copper, so connectivity has to see it.
    pub outlines: Vec<(String, Vec<Point>)>,
    /// Whether the zone is set to fill at all.
    pub filled: bool,
}

/// Read a zone's pour outlines, keyed by layer.
///
/// A zone names one `(polygon (pts ...))` per layer, and a multi-layer zone
/// repeats the same outline once per layer it covers.
fn zone_outlines(zone: &Node) -> Vec<(String, Vec<Point>)> {
    zone.find_all("polygon")
        .filter_map(|polygon| {
            let points = polygon.find("pts")?;
            let vertices: Vec<Point> = points
                .find_all("xy")
                .filter_map(|xy| {
                    let x = xy
                        .body()
                        .first()
                        .and_then(Node::as_str)?
                        .parse::<f64>()
                        .ok()?;
                    let y = xy
                        .body()
                        .get(1)
                        .and_then(Node::as_str)?
                        .parse::<f64>()
                        .ok()?;
                    Some(Point::new(mm_to_nm(x), mm_to_nm(y)))
                })
                .collect();
            if vertices.len() < 3 {
                return None;
            }
            Some((String::new(), vertices))
        })
        .flat_map(|(_, vertices)| {
            zone.layer_names()
                .into_iter()
                .map(move |layer| (layer, vertices.clone()))
        })
        .collect()
}

/// Whether a zone is set to fill.
///
/// `(fill yes ...)` is explicit; a zone with no `(fill ...)` block is left
/// unfilled by KiCad and is not copper.
fn zone_fill_enabled(zone: &Node) -> bool {
    match zone.find("fill") {
        Some(fill) => fill.body().first().and_then(Node::as_str) != Some("no"),
        None => false,
    }
}

/// A routed board as read back from disk.
#[derive(Debug, Clone, PartialEq)]
pub struct PcbBoard {
    pub version: Option<String>,
    pub generator: Option<String>,
    /// Declared layer names in file order.
    pub layers: Vec<String>,
    /// Net code to net name.
    pub nets: BTreeMap<u32, String>,
    pub footprints: Vec<Footprint>,
    pub segments: Vec<Segment>,
    pub vias: Vec<Via>,
    pub zones: Vec<Zone>,
    /// `(start, end)` of every `Edge.Cuts` graphic.
    pub edge_cuts: Vec<(Point, Point)>,
}

impl PcbBoard {
    /// Read a board from file text.
    ///
    /// # Errors
    /// Returns [`PcbParseError`] when the file is not a readable
    /// `kicad_pcb` tree. A malformed candidate is never treated as an
    /// empty one: an empty board passes every "is anything missing?" check.
    pub fn parse(text: &str) -> Result<Self, PcbParseError> {
        let root = parse_sexpr(text)?;
        if root.head() != Some("kicad_pcb") {
            return Err(PcbParseError {
                offset: 0,
                detail: format!(
                    "expected a `kicad_pcb` document, found `{}`",
                    root.head().unwrap_or("<atom>")
                ),
            });
        }

        let mut board = Self {
            version: root.child_atom("version").map(ToString::to_string),
            generator: root.child_atom("generator").map(ToString::to_string),
            layers: Vec::new(),
            nets: BTreeMap::new(),
            footprints: Vec::new(),
            segments: Vec::new(),
            vias: Vec::new(),
            zones: Vec::new(),
            edge_cuts: Vec::new(),
        };

        board.layers = root.layer_names();

        // Net codes come from the net table, which is written
        // `(net <code> "<name>")`. Only that shape declares a net; a
        // name-only `(net "<name>")` is a pad or track *referring* to a net,
        // and treating one as a declaration invents a code for it — which
        // renumbers every net after it and makes the whole board look
        // renetted against its baseline.
        for net in root.find_all("net") {
            let Some(first) = net.body().first().and_then(Node::as_str) else {
                continue;
            };
            let Some(code) = first.parse::<u32>().ok() else {
                continue;
            };
            let name = net
                .body()
                .get(1)
                .and_then(Node::as_str)
                .unwrap_or_default()
                .to_string();
            board.nets.insert(code, name);
        }

        // Some engines (KiCadRoutingTools among them) write a board with no
        // net table at all, binding nets by name on each pad and track. Those
        // names are collected here and reconciled into codes once everything
        // else has been parsed; without it every pad reads as netless and a
        // correctly routed board is reported as one whose nets went missing.

        for footprint in root.find_all("footprint") {
            board.footprints.push(parse_footprint(footprint));
        }
        for segment in root.find_all("segment") {
            if let Some(parsed) = parse_segment(segment) {
                board.segments.push(parsed);
            }
        }
        for via in root.find_all("via") {
            if let Some(parsed) = parse_via(via) {
                board.vias.push(parsed);
            }
        }
        for zone in root.find_all("zone") {
            // A zone's net is written `(net <code>)`, `(net <code> "<name>")`,
            // or — on a board with no net table, as KiCadRoutingTools writes
            // — `(net "<name>")`. `net_name` is a separate optional child.
            // Reading only the numeric form left the pour's net unset, so it
            // never matched its own net and a ground plane read as no copper:
            // every pad on that net was then reported stranded.
            let (code, bound_name) = match zone.net_binding("net") {
                Some((code, name)) => (code, name),
                None => (None, None),
            };
            board.zones.push(Zone {
                net: code.and_then(|c| u32::try_from(c).ok()),
                net_name: bound_name
                    .or_else(|| zone.child_atom("net_name").map(ToString::to_string)),
                layers: zone.layer_names(),
                outlines: zone_outlines(zone),
                filled: zone_fill_enabled(zone),
            });
        }
        for graphic in root
            .body()
            .iter()
            .filter(|n| matches!(n.head(), Some("gr_line" | "gr_rect" | "gr_arc")))
        {
            collect_edge_cuts(graphic, &mut board.edge_cuts);
        }

        board.reconcile_name_only_nets();

        Ok(board)
    }

    /// Give every net that is referred to only by name a code.
    ///
    /// A board with no net table — as KiCadRoutingTools writes — binds nets
    /// by name on each pad, track, via and zone, and declares none. Those
    /// names are gathered here and numbered, because without a code every
    /// reference reads as netless and a correctly routed board looks like one
    /// whose nets went missing.
    ///
    /// A board that *does* have a table keeps its own numbering, which is
    /// what makes it comparable with its baseline; renumbering it would
    /// report every pad as renetted.
    fn reconcile_name_only_nets(&mut self) {
        if !self.nets.is_empty() && self.nets.len() > 1 {
            return;
        }
        let mut referenced: BTreeSet<String> = BTreeSet::new();
        for footprint in &self.footprints {
            for pad in &footprint.pads {
                if let Some(name) = &pad.net_name {
                    referenced.insert(name.clone());
                }
            }
        }
        for segment in &self.segments {
            if let Some(name) = &segment.net_name {
                referenced.insert(name.clone());
            }
        }
        for via in &self.vias {
            if let Some(name) = &via.net_name {
                referenced.insert(name.clone());
            }
        }
        for zone in &self.zones {
            if let Some(name) = &zone.net_name {
                referenced.insert(name.clone());
            }
        }
        referenced.remove("");
        if referenced.is_empty() {
            return;
        }

        let mut codes: BTreeMap<String, u32> = BTreeMap::new();
        for (next, name) in (1u32..).zip(referenced.iter()) {
            codes.insert(name.clone(), next);
            if !self.nets.values().any(|existing| existing == name) {
                self.nets.insert(next, name.clone());
            }
        }
        self.rebind_nets_by_name(&codes);
    }

    /// Re-key net bindings that carry only a name.
    ///
    /// Assigns each name the code from `codes` on every pad, segment and via
    /// that names it, so a board written without a net table compares and
    /// validates like one that has it.
    fn rebind_nets_by_name(&mut self, codes: &BTreeMap<String, u32>) {
        for footprint in &mut self.footprints {
            for pad in &mut footprint.pads {
                if let Some(name) = &pad.net_name {
                    pad.net = codes.get(name).copied();
                }
            }
        }
        for segment in &mut self.segments {
            if let Some(name) = &segment.net_name {
                segment.net = codes.get(name).copied();
            }
        }
        for via in &mut self.vias {
            if let Some(name) = &via.net_name {
                via.net = codes.get(name).copied();
            }
        }
        for zone in &mut self.zones {
            if zone.net.is_none() {
                if let Some(name) = &zone.net_name {
                    zone.net = codes.get(name).copied();
                }
            }
        }
    }

    /// Every pad on the board.
    pub fn pads(&self) -> impl Iterator<Item = &Pad> {
        self.footprints.iter().flat_map(|f| f.pads.iter())
    }

    /// Footprint reference designators, sorted.
    #[must_use]
    pub fn references(&self) -> Vec<String> {
        let mut refs: Vec<String> = self
            .footprints
            .iter()
            .map(|f| f.reference.clone())
            .collect();
        refs.sort();
        refs
    }

    /// Net names declared on the board, excluding KiCad's net 0.
    #[must_use]
    pub fn net_names(&self) -> BTreeSet<String> {
        self.nets
            .iter()
            .filter(|(code, _)| **code != 0)
            .map(|(_, name)| name.clone())
            .collect()
    }

    /// Copper-layer names, i.e. everything except the technical layers.
    #[must_use]
    pub fn copper_layers(&self) -> Vec<String> {
        self.layers
            .iter()
            .filter(|l| l.ends_with(".Cu") || l.ends_with(".CuIn"))
            .cloned()
            .collect()
    }

    /// Total copper length in millimetres.
    #[must_use]
    pub fn wire_length_mm(&self) -> f64 {
        let nm: i64 = self.segments.iter().map(segment_length_nm).sum();
        nm as f64 / NM_PER_MM
    }
}

fn segment_length_nm(segment: &Segment) -> i64 {
    let dx = segment.end.x_nm - segment.start.x_nm;
    let dy = segment.end.y_nm - segment.start.y_nm;
    // Integer square root of a sum of squares, via Newton's method on the
    // f64 estimate. Board geometry is far inside the exactly-representable
    // range, so the estimate only needs to be close.
    let estimate = ((dx as f64) * (dx as f64) + (dy as f64) * (dy as f64)).sqrt();
    if !estimate.is_finite() {
        return 0;
    }
    estimate.round() as i64
}

fn parse_point(node: &Node, key: &str) -> Option<Point> {
    let at = node.find(key)?;
    let x = at
        .body()
        .first()
        .and_then(Node::as_str)?
        .parse::<f64>()
        .ok()?;
    let y = at
        .body()
        .get(1)
        .and_then(Node::as_str)?
        .parse::<f64>()
        .ok()?;
    Some(Point::new(mm_to_nm(x), mm_to_nm(y)))
}

fn parse_footprint(node: &Node) -> Footprint {
    let lib_id = node
        .body()
        .first()
        .and_then(Node::as_str)
        .unwrap_or_default()
        .to_string();
    let at = parse_point(node, "at").unwrap_or_default();
    let rotation_deg = node
        .find("at")
        .and_then(|n| n.body().get(2).and_then(Node::as_str))
        .and_then(|s| s.parse::<f64>().ok())
        .unwrap_or(0.0);
    let layer = node
        .child_atom("layer")
        .map_or_else(|| "F.Cu".to_string(), ToString::to_string);

    // A footprint on the bottom layer is mirrored, so its pad offsets
    // negate in y. Ignoring this places every bottom-side pad at the
    // wrong spot and makes the connectivity pass report nets open that
    // are perfectly routed.
    let mirrored = layer.starts_with('B');
    // A footprint's `(at x y angle)` angle is anticlockwise *on screen*, and
    // KiCad's y axis points down, so a pad offset transforms by -angle:
    //
    //     x' =  x cos + y sin
    //     y' = -x sin + y cos
    //
    // Rotating by +angle instead puts every pad with a non-zero offset on
    // the wrong side of its footprint. It survived because the corpus is
    // mostly symmetric two-pad passives, where +90 and -90 produce the same
    // *set* of positions and only swap which pad is which, so nets still
    // close. An asymmetric part exposes it at once: on a 1x2 JST rotated
    // 90, pad 2 was read 5 mm from where its copper is, and the net read
    // open against a board the engine had routed correctly.
    let cos = rotation_deg.to_radians().cos();
    let sin = rotation_deg.to_radians().sin();

    let pads = node
        .find_all("pad")
        .filter_map(|pad| {
            let number = pad.body().first().and_then(Node::as_str)?.to_string();
            let kind = pad
                .body()
                .get(1)
                .and_then(Node::as_str)
                .unwrap_or("")
                .to_string();
            let shape = pad
                .body()
                .get(2)
                .and_then(Node::as_str)
                .unwrap_or("")
                .to_string();
            let local = parse_point(pad, "at").unwrap_or_default();
            let x_nm = (local.x_nm as f64 * cos + local.y_nm as f64 * sin).round() as i64;
            let y_nm = (local.y_nm as f64 * cos - local.x_nm as f64 * sin).round() as i64;
            let y_nm = if mirrored { -y_nm } else { y_nm };
            // A pad's `(at x y angle)` angle is relative to its footprint,
            // so the board-frame orientation is the sum. Mirroring a
            // footprint onto the back reflects its pads in y, which negates
            // the angle just as it negates the offset above.
            let local_rotation_deg = pad
                .find("at")
                .and_then(|n| n.body().get(2).and_then(Node::as_str))
                .and_then(|s| s.parse::<f64>().ok())
                .unwrap_or(0.0);
            // Negated for the same reason as the offset above: the pad's own
            // axes turn with its footprint, in the same y-down sense.
            let rotation_deg = if mirrored {
                rotation_deg + local_rotation_deg
            } else {
                -(rotation_deg + local_rotation_deg)
            };
            let size = pad.find("size");
            let size_nm = (
                size.and_then(|s| s.body().first())
                    .and_then(Node::as_str)
                    .and_then(|s| s.parse::<f64>().ok())
                    .map_or(0, mm_to_nm),
                size.and_then(|s| s.body().get(1))
                    .and_then(Node::as_str)
                    .and_then(|s| s.parse::<f64>().ok())
                    .map_or(0, mm_to_nm),
            );
            let layers = pad.layer_names();
            let (net, net_name) = match pad.net_binding("net") {
                Some((code, name)) => (code.and_then(|c| u32::try_from(c).ok()), name),
                None => (None, None),
            };
            Some(Pad {
                footprint: String::new(),
                number,
                kind,
                shape,
                at: Point::new(at.x_nm + x_nm, at.y_nm + y_nm),
                size_nm,
                rotation_deg,
                layers,
                net,
                net_name,
            })
        })
        .map(|mut pad| {
            pad.footprint = String::new();
            pad
        })
        .collect();

    let reference = node.property("Reference").unwrap_or_default().to_string();

    Footprint {
        reference,
        lib_id,
        at,
        layer,
        rotation_deg,
        pads,
    }
    .with_pad_references()
}

impl Footprint {
    /// Stamp the owning reference onto each pad.
    #[must_use]
    fn with_pad_references(mut self) -> Self {
        let reference = self.reference.clone();
        for pad in &mut self.pads {
            pad.footprint.clone_from(&reference);
        }
        self
    }
}

impl From<Point> for (i64, i64) {
    fn from(p: Point) -> Self {
        (p.x_nm, p.y_nm)
    }
}

fn parse_segment(node: &Node) -> Option<Segment> {
    Some(Segment {
        net: node.child_i64("net").and_then(|n| u32::try_from(n).ok()),
        net_name: node
            .find("net")
            .and_then(|n| n.body().first())
            .and_then(Node::as_str)
            .map(ToString::to_string),
        layer: node
            .child_atom("layer")
            .map_or_else(|| "F.Cu".to_string(), ToString::to_string),
        start: parse_point(node, "start")?,
        end: parse_point(node, "end")?,
        width_nm: node.child_f64("width").map_or(0, mm_to_nm),
    })
}

fn parse_via(node: &Node) -> Option<Via> {
    Some(Via {
        net: node.child_i64("net").and_then(|n| u32::try_from(n).ok()),
        net_name: node
            .find("net")
            .and_then(|n| n.body().first())
            .and_then(Node::as_str)
            .map(ToString::to_string),
        at: parse_point(node, "at")?,
        size_nm: node.child_f64("size").map_or(0, mm_to_nm),
        drill_nm: node.child_f64("drill").map_or(0, mm_to_nm),
        layers: node.layer_names(),
    })
}

fn collect_edge_cuts(node: &Node, out: &mut Vec<(Point, Point)>) {
    let layer = node.child_atom("layer");
    if !matches!(layer, Some("Edge.Cuts")) {
        return;
    }
    let (start, end) = match node.head() {
        Some("gr_line") => (parse_point(node, "start"), parse_point(node, "end")),
        Some("gr_rect") => {
            let start = parse_point(node, "start");
            let end = parse_point(node, "end");
            (start, end)
        }
        _ => (None, None),
    };
    if let (Some(start), Some(end)) = (start, end) {
        out.push((start, end));
    }
}

/// A short board used as a parser fixture.
///
/// Written by hand rather than exported by Synth so the reader's tests do
/// not depend on the exporter's own output being correct — a reader
/// tested only against its own writer proves nothing.
///
/// Hand-writing has its own trap: U1's `B.Cu` segment used to end at
/// (30, 21), the point the reader's own rotation arithmetic reported for
/// pad 1, so the fixture certified the sign error it should have caught.
/// The pad is at (30, 19). Coordinates here are worth checking against a
/// board a router actually produced.
pub const SAMPLE_BOARD: &str = r#"(kicad_pcb
  (version 20260206)
  (generator "synth-eda")
  (layers
    (0 "F.Cu" signal)
    (31 "B.Cu" signal)
    (44 "Edge.Cuts" user)
  )
  (net 0 "")
  (net 1 "GND")
  (net 2 "SDA")
  (footprint "Resistor_SMD:R_0603_1608Metric"
    (layer "F.Cu")
    (at 10 20)
    (property "Reference" "R1" (at 0 -1) (layer "F.SilkS"))
    (pad "1" smd roundrect (at -0.825 0) (size 0.8 0.95)
      (layers "F.Cu" "F.Paste" "F.Mask") (net 1 "GND"))
    (pad "2" smd roundrect (at 0.825 0) (size 0.8 0.95)
      (layers "F.Cu" "F.Paste" "F.Mask") (net 2 "SDA"))
  )
  (footprint "Package_QFN:QFN-32"
    (layer "B.Cu")
    (at 30 20 90)
    (property "Reference" "U1" (at 0 -1) (layer "B.SilkS"))
    (pad "1" smd roundrect (at -1 0) (size 0.6 0.3)
      (layers "B.Cu" "B.Paste" "B.Mask") (net 2 "SDA"))
  )
  (segment (start 10.825 20) (end 15 20) (width 0.25) (layer "F.Cu") (net 2))
  (segment (start 15 20) (end 15 18) (width 0.25) (layer "F.Cu") (net 2))
  (via (at 15 18) (size 0.8) (drill 0.4) (layers "F.Cu" "B.Cu") (net 2))
  (segment (start 15 18) (end 30 19) (width 0.25) (layer "B.Cu") (net 2))
  (gr_line (start 0 0) (end 40 0) (layer "Edge.Cuts") (width 0.1))
  (gr_line (start 0 30) (end 40 30) (layer "Edge.Cuts") (width 0.1))
)
"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_sample_board_round_trips_into_topology_and_copper() {
        let board = PcbBoard::parse(SAMPLE_BOARD).expect("sample parses");
        assert_eq!(board.version.as_deref(), Some("20260206"));
        assert_eq!(board.generator.as_deref(), Some("synth-eda"));
        assert_eq!(board.references(), vec!["R1".to_string(), "U1".to_string()]);
        assert_eq!(board.segments.len(), 3);
        assert_eq!(board.vias.len(), 1);
        assert_eq!(board.edge_cuts.len(), 2);
    }

    #[test]
    fn a_board_with_no_net_table_still_yields_usable_net_codes() {
        // KiCadRoutingTools writes a board with no `(net <code> "<name>")`
        // table at all, binding nets by name on each pad and track. Reading
        // only the table made every net invisible, so a correctly routed
        // board was reported as one whose nets had gone missing.
        let text = r#"(kicad_pcb
  (version 20260206)
  (generator "pcbnew")
  (layers (0 "F.Cu" signal) (44 "Edge.Cuts" user))
  (footprint "R:R_0603"
    (layer "F.Cu") (at 10 20)
    (property "Reference" "R1" (at 0 -1) (layer "F.SilkS"))
    (pad "1" smd roundrect (at -0.825 0) (size 0.8 0.95)
      (layers "F.Cu" "F.Paste" "F.Mask") (net "net_0"))
    (pad "2" smd roundrect (at 0.825 0) (size 0.8 0.95)
      (layers "F.Cu" "F.Paste" "F.Mask") (net "net_1")))
  (footprint "R:R_0603"
    (layer "F.Cu") (at 20 20)
    (property "Reference" "R2" (at 0 -1) (layer "F.SilkS"))
    (pad "1" smd roundrect (at -0.825 0) (size 0.8 0.95)
      (layers "F.Cu" "F.Paste" "F.Mask") (net "net_0"))
    (pad "2" smd roundrect (at 0.825 0) (size 0.8 0.95)
      (layers "F.Cu" "F.Paste" "F.Mask") (net 0 "")))
  (segment (start 9.175 20) (end 19.175 20) (width 0.25)
    (layer "F.Cu") (net "net_0"))
  (gr_line (start 0 0) (end 40 0) (layer "Edge.Cuts") (width 0.1))
)"#;
        let board = PcbBoard::parse(text).expect("table-less board parses");
        assert_eq!(board.nets.len(), 2, "{:?}", board.nets);
        assert!(
            board.nets.values().any(|n| n == "net_0"),
            "the named net must survive: {:?}",
            board.nets
        );
        // The pad and the track must agree on the reconstructed code, or the
        // net reads as two islands.
        let r1_1 = board.pads().find(|p| p.id() == "R1.1").expect("R1 pad 1");
        let r2_1 = board.pads().find(|p| p.id() == "R2.1").expect("R2 pad 1");
        assert_eq!(r1_1.net, r2_1.net, "both pads must share a code");
        assert_eq!(board.segments[0].net, r1_1.net, "track shares the code");
    }
    #[test]
    fn pads_carry_their_net_layer_and_absolute_position() {
        let board = PcbBoard::parse(SAMPLE_BOARD).expect("sample parses");
        let r1 = board
            .footprints
            .iter()
            .find(|f| f.reference == "R1")
            .expect("R1");
        let pad2 = r1.pads.iter().find(|p| p.number == "2").expect("pad 2");
        assert_eq!(pad2.net, Some(2));
        assert_eq!(pad2.net_name.as_deref(), Some("SDA"));
        assert!(pad2.on_layer("F.Cu"));
        assert!(!pad2.on_layer("B.Cu"));
        // R1 sits at (10, 20); pad 2 is 0.825 mm to its right.
        assert_eq!(pad2.at, Point::new(mm_to_nm(10.825), mm_to_nm(20.0)));
        assert_eq!(pad2.id(), "R1.2");
    }

    #[test]
    fn a_rotated_bottom_side_pad_is_placed_in_board_coordinates() {
        // U1 is on B.Cu at (30, 20) rotated 90 degrees. Getting this
        // wrong puts every bottom-side pad in the wrong place and makes
        // correctly routed nets look open.
        let board = PcbBoard::parse(SAMPLE_BOARD).expect("sample parses");
        let u1 = board
            .footprints
            .iter()
            .find(|f| f.reference == "U1")
            .expect("U1");
        assert_eq!(u1.layer, "B.Cu");
        assert_eq!(u1.rotation_deg, 90.0);
        let pad1 = u1.pads.iter().find(|p| p.number == "1").expect("pad 1");
        // A local offset of (-1, 0) rotates to (0, +1) in KiCad's y-down
        // sense, then mirrors in y for the bottom side: (30, 19).
        //
        // The front-side half of this transform is measured against copper
        // a router produced. The mirror composition is not: the placer puts
        // every footprint on the front, so no board exercises it.
        assert_eq!(pad1.at, Point::new(mm_to_nm(30.0), mm_to_nm(19.0)));
    }

    #[test]
    fn segment_and_via_geometry_is_read() {
        let board = PcbBoard::parse(SAMPLE_BOARD).expect("sample parses");
        let track = &board.segments[0];
        assert_eq!(track.layer, "F.Cu");
        assert_eq!(track.net, Some(2));
        assert_eq!(track.width_nm, mm_to_nm(0.25));
        let via = &board.vias[0];
        assert_eq!(via.size_nm, mm_to_nm(0.8));
        assert_eq!(via.drill_nm, mm_to_nm(0.4));
        assert!(via.layers.contains(&"F.Cu".to_string()));
        assert!(via.layers.contains(&"B.Cu".to_string()));
    }

    #[test]
    fn copper_layers_exclude_technical_layers() {
        let board = PcbBoard::parse(SAMPLE_BOARD).expect("sample parses");
        assert_eq!(
            board.copper_layers(),
            vec!["F.Cu".to_string(), "B.Cu".to_string()]
        );
    }

    #[test]
    fn wire_length_sums_every_segment() {
        let board = PcbBoard::parse(SAMPLE_BOARD).expect("sample parses");
        // 4.175 mm + 2 mm + the diagonal (15, 18)-(30, 19).
        let expected = 4.175 + 2.0 + (15.0f64 * 15.0 + 1.0).sqrt();
        assert!(
            (board.wire_length_mm() - expected).abs() < 0.001,
            "{}",
            board.wire_length_mm()
        );
    }

    #[test]
    fn comments_and_escaped_quotes_do_not_confuse_the_parser() {
        let text = r#"(kicad_pcb
          (version 20260206) ; a comment with ( unbalanced parens
          (generator "synth \"quoted\"")
          (net 1 "a\"b")
        )"#;
        let board = PcbBoard::parse(text).expect("parses");
        assert_eq!(board.generator.as_deref(), Some(r#"synth "quoted""#));
        assert_eq!(board.nets.get(&1).map(String::as_str), Some(r#"a"b"#));
    }

    #[test]
    fn a_non_pcb_document_is_rejected_rather_than_read_as_empty() {
        // An empty board passes every "is anything missing?" check, so a
        // failed parse must never degrade into an empty board.
        let err = PcbBoard::parse("(kicad_sch (version 1))").expect_err("not a pcb");
        assert!(err.detail.contains("kicad_pcb"), "{err}");
    }

    #[test]
    fn unbalanced_parens_are_reported_with_an_offset() {
        let err = parse_sexpr("(kicad_pcb (version 1)").expect_err("unclosed");
        assert_eq!(err.offset, "(kicad_pcb (version 1)".len());
        let err = parse_sexpr("(kicad_pcb)) ").expect_err("extra close");
        assert!(err.detail.contains("unbalanced"), "{err}");
    }

    #[test]
    fn an_unterminated_string_is_reported() {
        let err = parse_sexpr(r#"(kicad_pcb (generator "oops)"#).expect_err("unterminated");
        assert!(err.detail.contains("unterminated"), "{err}");
    }

    #[test]
    fn a_pad_without_a_net_is_read_as_unconnected() {
        let board = PcbBoard::parse(SAMPLE_BOARD).expect("sample parses");
        let u1 = board
            .footprints
            .iter()
            .find(|f| f.reference == "U1")
            .expect("U1");
        assert_eq!(u1.pads[0].net, Some(2));
        // Every pad in the sample carries a net; the unconnected case is
        // covered by the zone/net tests with a net-0 pad.
        assert!(board.pads().all(|p| p.net.is_some()));
    }

    #[test]
    fn nanometre_conversion_rounds_to_the_nearest_nanometre() {
        // Truncating here would put two coordinates that describe the same
        // point into different buckets, and every net would read as open.
        assert_eq!(mm_to_nm(1.0), 1_000_000);
        assert_eq!(mm_to_nm(0.127), 127_000);
        assert_eq!(mm_to_nm(-0.5), -500_000);
        assert_eq!(mm_to_nm(f64::NAN), 0);
    }
}
